// delegates.js
export const DELEGATES_DATA = [
  {"name": "Albania", "code": "al", "delegate": "Flavia Harizaj", "imgCode": "alb"},
  {"name": "Angola", "code": "ao", "delegate": "Maria Cunha", "imgCode": "ang"},
  {"name": "Argentina", "code": "ar", "delegate": "Aldana Masset", "imgCode": "arg"},
  {"name": "Armenia", "code": "am", "delegate": "Peggy Garabekian", "imgCode": "arm"},
  {"name": "Aruba", "code": "aw", "delegate": "Hannah Arends", "imgCode": "aru"},
  {"name": "Australia", "code": "au", "delegate": "Lexie Brant", "imgCode": "aus"},
  {"name": "Bahamas", "code": "bs", "delegate": "Malique Bowe", "imgCode": "bah"},
  {"name": "Bangladesh", "code": "bd", "delegate": "Tangia Methila", "imgCode": "ban"},
  {"name": "Bielorrusia", "code": "by", "delegate": "Alena Kucheruk", "imgCode": "belg"},
  {"name": "Bélgica", "code": "be", "delegate": "Karen Jansen", "imgCode": "bel"},
  {"name": "Belice", "code": "bz", "delegate": "Isabella Zabaneh", "imgCode": "bez"},
  {"name": "Bolivia", "code": "bo", "delegate": "Yessica Hausermann", "imgCode": "bol"},
  {"name": "Bonaire", "code": "bq", "delegate": "Nicole Peiliker", "imgCode": "bon"},
  {"name": "Botsuana", "code": "bw", "delegate": "Lillian Andries", "imgCode": "bot"},
  {"name": "Brasil", "code": "br", "delegate": "Gabriela Lacerda", "imgCode": "bra"},
  {"name": "Islas Vírgenes GB", "code": "vg", "delegate": "Olivia Freeman", "imgCode": "bvi"},
  {"name": "Bulgaria", "code": "bg", "delegate": "Gaby Guha", "imgCode": "bul"},
  {"name": "Cabo Verde", "code": "cv", "delegate": "Tahiti Seymour", "imgCode": "cap"},
  {"name": "Camboya", "code": "kh", "delegate": "Nearysocheata Thai", "imgCode": "cam"},
  {"name": "Canadá", "code": "ca", "delegate": "Jaime VandenBerg", "imgCode": "can"},
  {"name": "Islas Caimán", "code": "ky", "delegate": "Tahiti Seymour", "imgCode": "cay"},
  {"name": "Chile", "code": "cl", "delegate": "Inna Moll", "imgCode": "chl"},
  {"name": "China", "code": "cn", "delegate": "Zhao Na", "imgCode": "chn"},
  {"name": "Colombia", "code": "co", "delegate": "Vanessa Pulgarin", "imgCode": "col"},
  {"name": "Costa Rica", "code": "cr", "delegate": "Mahyla Roth", "imgCode": "cos"},
  {"name": "Costa de Marfil", "code": "ci", "delegate": "Olivia Yace", "imgCode": "cot"},
  {"name": "Croacia", "code": "hr", "delegate": "Laura Gnjatovic", "imgCode": "cro"},
  {"name": "Cuba", "code": "cu", "delegate": "Lina Luaces", "imgCode": "cub"},
  {"name": "Curazao", "code": "cw", "delegate": "Camille Thomas", "imgCode": "cur"},
  {"name": "Rep Checa", "code": "cz", "delegate": "Michaela Tomanova", "imgCode": "cze"},
  {"name": "Rep Dem Congo", "code": "cd", "delegate": "Dorcas Dienda", "imgCode": "drc"},
  {"name": "Dinamarca", "code": "dk", "delegate": "Monique Sonne", "imgCode": "den"},
  {"name": "Rep Dominicana", "code": "do", "delegate": "Jennifer Ventura", "imgCode": "dom"},
  {"name": "Ecuador", "code": "ec", "delegate": "Nadia Mejia", "imgCode": "ecu"},
  {"name": "Egipto", "code": "eg", "delegate": "Sabrina Maged", "imgCode": "egy"},
  {"name": "El Salvador", "code": "sv", "delegate": "Giulia Zanoni", "imgCode": "els"},
  {"name": "Guinea Ecuatorial", "code": "gq", "delegate": "Carmen Ismelda Avomo", "imgCode": "equ"},
  {"name": "Estonia", "code": "ee", "delegate": "Brigitta Schaback", "imgCode": "est"},
  {"name": "Finlandia", "code": "fi", "delegate": "Sarah Dzafce", "imgCode": "fin"},
  {"name": "Francia", "code": "fr", "delegate": "Ève Gilles", "imgCode": "fra"},
  {"name": "Ghana", "code": "gh", "delegate": "Andromeda Peters", "imgCode": "gha"},
  {"name": "Gran Bretaña", "code": "gb", "delegate": "Danielle Latimer", "imgCode": "gb"},
  {"name": "Grecia", "code": "gr", "delegate": "Mary Chatzipavlou", "imgCode": "gre"},
  {"name": "Guadalupe", "code": "gp", "delegate": "Ophely Mezino", "imgCode": "guad"},
  {"name": "Guatemala", "code": "gt", "delegate": "Raschel Paz", "imgCode": "guat"},
  {"name": "Guinea", "code": "gn", "delegate": "Tiguidanke Berete", "imgCode": "gui"},
  {"name": "Guyana", "code": "gy", "delegate": "Chandini Baljor", "imgCode": "guy"},
  {"name": "Haití", "code": "ht", "delegate": "Melissa Sapini", "imgCode": "hai"},
  {"name": "Honduras", "code": "hn", "delegate": "Alejandra Fuentes", "imgCode": "hon"},
  {"name": "Hong Kong", "code": "hk", "delegate": "Lizzie Li", "imgCode": "hk"},
  {"name": "Hungría", "code": "hu", "delegate": "Kincs Dezsenyi", "imgCode": "hun"},
  {"name": "India", "code": "in", "delegate": "Manika Vishwakarma", "imgCode": "ind"},
  {"name": "Indonesia", "code": "id", "delegate": "Sanly Liu", "imgCode": "indo"},
  {"name": "Irak", "code": "iq", "delegate": "Hanin Al Qoreishy", "imgCode": "iraq"},
  {"name": "Irlanda", "code": "ie", "delegate": "Aadya Srivastava", "imgCode": "ire"},
  {"name": "Israel", "code": "il", "delegate": "Melanie Shiraz", "imgCode": "isr"},
  {"name": "Italia", "code": "it", "delegate": "Lucilla Nori", "imgCode": "ita"},
  {"name": "Jamaica", "code": "jm", "delegate": "Gabrielle Henry", "imgCode": "jam"},
  {"name": "Japón", "code": "jp", "delegate": "Kaori Hashimoto", "imgCode": "jap"},
  {"name": "Kazajistán", "code": "kz", "delegate": "Dana Almassova", "imgCode": "kaz"},
  {"name": "Corea del Sur", "code": "kr", "delegate": "Soo-yeon Lee", "imgCode": "kor"},
  {"name": "Kosovo", "code": "xk", "delegate": "Dorea Shala", "imgCode": "kos"},
  {"name": "Kirguistán", "code": "kg", "delegate": "Mary Kuvakova", "imgCode": "kyr"},
  {"name": "Laos", "code": "la", "delegate": "Lattana Munvilay", "imgCode": "lao"},
  {"name": "Latvia", "code": "lv", "delegate": "Meldra Rosenberg", "imgCode": "lat"},
  {"name": "Líbano", "code": "lb", "delegate": "Sarah Bou Jaoude", "imgCode": "leb"},
  {"name": "Macao", "code": "mo", "delegate": "Kris Fong", "imgCode": "mac"},
  {"name": "Malasia", "code": "my", "delegate": "Chloe Lim", "imgCode": "mal"},
  {"name": "Malta", "code": "mt", "delegate": "Julia Cluett", "imgCode": "malt"},
  {"name": "Martinica", "code": "mq", "delegate": "Celya Abatucci", "imgCode": "mart"},
  {"name": "Mauricio", "code": "mu", "delegate": "Aurelie Alcindor", "imgCode": "mau"},
  {"name": "Mayotte", "code": "yt", "delegate": "Nourya Aboutoihi", "imgCode": "may"},
  {"name": "México", "code": "mx", "delegate": "Fatima Bosch", "imgCode": "mex"},
  {"name": "MU Latina", "code": "us", "delegate": "Yamilex Hernandez", "imgCode": "latina"},
  {"name": "Moldavia", "code": "md", "delegate": "Mariana Ignat", "imgCode": "mol"},
  {"name": "Myanmar", "code": "mm", "delegate": "Myat Yadanar Soe", "imgCode": "mya"},
  {"name": "Namibia", "code": "na", "delegate": "Johanna Swartbooi", "imgCode": "nam"},
  {"name": "Nepal", "code": "np", "delegate": "Sanya Adhikari", "imgCode": "nep"},
  {"name": "Países Bajos", "code": "nl", "delegate": "Nathalie Mogbelzada", "imgCode": "net"},
  {"name": "Nueva Zelanda", "code": "nz", "delegate": "Abbigail Sturgin", "imgCode": "nz"},
  {"name": "Nicaragua", "code": "ni", "delegate": "Itza Castillo", "imgCode": "nic"},
  {"name": "Nigeria", "code": "ng", "delegate": "Basil Onyinyechi", "imgCode": "nig"},
  {"name": "Noruega", "code": "no", "delegate": "Leonora Lysglimt-Rødland", "imgCode": "nor"},
  {"name": "Pakistán", "code": "pk", "delegate": "Roma Riaz", "imgCode": "pak"},
  {"name": "Palestina", "code": "ps", "delegate": "Nadeen Ayoub", "imgCode": "pal"},
  {"name": "Panamá", "code": "pa", "delegate": "Mirna Caballini", "imgCode": "pan"},
  {"name": "Paraguay", "code": "py", "delegate": "Yanina Gomez", "imgCode": "par"},
  {"name": "Perú", "code": "pe", "delegate": "Karla Bacigalupo", "imgCode": "per"},
  {"name": "Filipinas", "code": "ph", "delegate": "Ahtisa Manalo", "imgCode": "phi"},
  {"name": "Polonia", "code": "pl", "delegate": "Emily Reng", "imgCode": "pol"},
  {"name": "Portugal", "code": "pt", "delegate": "Camila Vitorino", "imgCode": "por"},
  {"name": "Puerto Rico", "code": "pr", "delegate": "Zashely Alicea", "imgCode": "pr"},
  {"name": "Rumania", "code": "ro", "delegate": "Catalina Jacob", "imgCode": "rom"},
  {"name": "Rusia", "code": "ru", "delegate": "Anastasia Venza", "imgCode": "rus"},
  {"name": "Ruanda", "code": "rw", "delegate": "Solange Keita", "imgCode": "rwa"},
  {"name": "Santa Lucía", "code": "lc", "delegate": "Shianne Smith", "imgCode": "stl"},
  {"name": "Senegal", "code": "sn", "delegate": "Camilla Diagne", "imgCode": "sen"},
  {"name": "Serbia", "code": "rs", "delegate": "Jelena Egorova", "imgCode": "ser"},
  {"name": "Singapur", "code": "sg", "delegate": "Annika Sager", "imgCode": "sin"},
  {"name": "Eslovaquia", "code": "sk", "delegate": "Viktoria Güllova", "imgCode": "slo"},
  {"name": "Eslovenia", "code": "si", "delegate": "Hana Klaut", "imgCode": "slv"},
  {"name": "South Africa", "code": "za", "delegate": "Melissa Nayimuli", "imgCode": "sa"},
  {"name": "España", "code": "es", "delegate": "Andrea Valero", "imgCode": "spa"},
  {"name": "Sri Lanka", "code": "lk", "delegate": "Lihasha White", "imgCode": "sri"},
  {"name": "Suecia", "code": "se", "delegate": "Daniella Lundqvist", "imgCode": "swe"},
  {"name": "Suiza", "code": "ch", "delegate": "Naima Acosta", "imgCode": "swi"},
  {"name": "Tanzania", "code": "tz", "delegate": "Naisae Yona", "imgCode": "tan"},
  {"name": "Tailandia", "code": "th", "delegate": "Praveenar Singh", "imgCode": "tha"},
  {"name": "Trinidad y Tobago", "code": "tt", "delegate": "Latifah Morris", "imgCode": "tri"},
  {"name": "Turquía", "code": "tr", "delegate": "Ceren Arslan", "imgCode": "tur"},
  {"name": "Turks & Caicos", "code": "tc", "delegate": "Bereniece Dickenson", "imgCode": "tnc"},
  {"name": "Ucrania", "code": "ua", "delegate": "Sofiya Tkachuk", "imgCode": "ukr"},
  {"name": "Emiratos Árabes", "code": "ae", "delegate": "Mariam Mohamed", "imgCode": "uae"},
  {"name": "Uruguay", "code": "uy", "delegate": "Valeria Baladan", "imgCode": "uru"},
  {"name": "Estados Unidos", "code": "us", "delegate": "Audrey Eckert", "imgCode": "usa"},
  {"name": "Islas Vírgenes US", "code": "vi", "delegate": "Britanny Robinson", "imgCode": "usvi"},
  {"name": "Venezuela", "code": "ve", "delegate": "Stephany Abasali", "imgCode": "ven"},
  {"name": "Vietnam", "code": "vn", "delegate": "Hng Giang Nguyn", "imgCode": "vie"},
  {"name": "Zambia", "code": "zm", "delegate": "Kunda Mwamulima", "imgCode": "zam"},
  {"name": "Zimbabue", "code": "zw", "delegate": "Lyshanda Moyas", "imgCode": "zim"}
];