// delegates.js
export const DELEGATES_DATA = [
  {"name": "Albania", "code": "al", "delegate": "Flavia Harizaj"},
  {"name": "Angola", "code": "ao", "delegate": "Maria Cunha"},
  {"name": "Argentina", "code": "ar", "delegate": "Aldana Masset"},
  {"name": "Armenia", "code": "am", "delegate": "Peggy Garabekian"},
  {"name": "Aruba", "code": "aw", "delegate": "Hannah Arends"},
  {"name": "Australia", "code": "au", "delegate": "Lexie Brant"},
  {"name": "Bahamas", "code": "bs", "delegate": "Malique Bowe"},
  {"name": "Bangladesh", "code": "bd", "delegate": "Tangia Methila"},
  {"name": "Bélgica", "code": "be", "delegate": "Karen Jansen"},
  {"name": "Belice", "code": "bz", "delegate": "Isabella Zabaneh"},
  {"name": "Bielorrusia", "code": "by", "delegate": "Alena Kucheruk"},
  {"name": "Bolivia", "code": "bo", "delegate": "Yessica Hausermann"},
  {"name": "Bonaire", "code": "bq", "delegate": "Nicole Peiliker"},
  {"name": "Botsuana", "code": "bw", "delegate": "Lillian Andries"},
  {"name": "Brasil", "code": "br", "delegate": "Gabriela Lacerda"},
  {"name": "Bulgaria", "code": "bg", "delegate": "Gaby Guha"},
  {"name": "Cabo Verde", "code": "cv", "delegate": "Tahiti Seymour"},
  {"name": "Islas Caimán", "code": "ky", "delegate": "Tahiti Seymour"},
  {"name": "Camboya", "code": "kh", "delegate": "Nearysocheata Thai"},
  {"name": "Camerún", "code": "cm", "delegate": "Josiane Golonga"},
  {"name": "Canadá", "code": "ca", "delegate": "Jaime VandenBerg"},
  {"name": "Chile", "code": "cl", "delegate": "Inna Moll"},
  {"name": "China", "code": "cn", "delegate": "Zhao Na"},
  {"name": "Colombia", "code": "co", "delegate": "Vanessa Pulgarin"},
  {"name": "Corea del Sur", "code": "kr", "delegate": "Soo-yeon Lee"},
  {"name": "Costa de Marfil", "code": "ci", "delegate": "Olivia Yace"},
  {"name": "Costa Rica", "code": "cr", "delegate": "Mahyla Roth"},
  {"name": "Croacia", "code": "hr", "delegate": "Laura Gnjatovic"},
  {"name": "Cuba", "code": "cu", "delegate": "Lina Luaces"},
  {"name": "Curazao", "code": "cw", "delegate": "Camille Thomas"},
  {"name": "Dinamarca", "code": "dk", "delegate": "Monique Sonne"},
  {"name": "Ecuador", "code": "ec", "delegate": "Nadia Mejia"},
  {"name": "Egipto", "code": "eg", "delegate": "Sabrina Maged"},
  {"name": "El Salvador", "code": "sv", "delegate": "Giulia Zanoni"},
  {"name": "Emiratos Árabes", "code": "ae", "delegate": "Mariam Mohamed"},
  {"name": "Eslovaquia", "code": "sk", "delegate": "Viktoria Güllova"},
  {"name": "Eslovenia", "code": "si", "delegate": "Hana Klaut"},
  {"name": "España", "code": "es", "delegate": "Andrea Valero"},
  {"name": "Estados Unidos", "code": "us", "delegate": "Audrey Eckert"},
  {"name": "MU Latina", "code": "us", "delegate": "Yamilex Hernandez"},
  {"name": "Estonia", "code": "ee", "delegate": "Brigitta Schaback"},
  {"name": "Filipinas", "code": "ph", "delegate": "Ahtisa Manalo"},
  {"name": "Finlandia", "code": "fi", "delegate": "Sarah Dzafce"},
  {"name": "Francia", "code": "fr", "delegate": "Ève Gilles"},
  {"name": "Ghana", "code": "gh", "delegate": "Andromeda Peters"},
  {"name": "Gran Bretaña", "code": "gb", "delegate": "Danielle Latimer"},
  {"name": "Grecia", "code": "gr", "delegate": "Mary Chatzipavlou"},
  {"name": "Guadalupe", "code": "gp", "delegate": "Ophely Mezino"},
  {"name": "Guatemala", "code": "gt", "delegate": "Raschel Paz"},
  {"name": "Guinea", "code": "gn", "delegate": "Tiguidanke Berete"},
  {"name": "Guyana", "code": "gy", "delegate": "Chandini Baljor"},
  {"name": "Haití", "code": "ht", "delegate": "Melissa Sapini"},
  {"name": "Honduras", "code": "hn", "delegate": "Alejandra Fuentes"},
  {"name": "Hong Kong", "code": "hk", "delegate": "Lizzie Li"},
  {"name": "Hungría", "code": "hu", "delegate": "Kincs Dezsenyi"},
  {"name": "India", "code": "in", "delegate": "Manika Vishwakarma"},
  {"name": "Indonesia", "code": "id", "delegate": "Sanly Liu"},
  {"name": "Irak", "code": "iq", "delegate": "Hanin Al Qoreishy"},
  {"name": "Irlanda", "code": "ie", "delegate": "Aadya Srivastava"},
  {"name": "Turks & Caicos", "code": "tc", "delegate": "Bereniece Dickenson"},
  {"name": "Islas Vírgenes GB", "code": "vg", "delegate": "Olivia Freeman"},
  {"name": "Islas Vírgenes US", "code": "vi", "delegate": "Britanny Robinson"},
  {"name": "Israel", "code": "il", "delegate": "Melanie Shiraz"},
  {"name": "Italia", "code": "it", "delegate": "Lucilla Nori"},
  {"name": "Jamaica", "code": "jm", "delegate": "Gabrielle Henry"},
  {"name": "Japón", "code": "jp", "delegate": "Kaori Hashimoto"},
  {"name": "Kazajistán", "code": "kz", "delegate": "Dana Almassova"},
  {"name": "Kosovo", "code": "xk", "delegate": "Dorea Shala"},
  {"name": "Kirguistán", "code": "kg", "delegate": "Mary Kuvakova"},
  {"name": "Laos", "code": "la", "delegate": "Lattana Munvilay"},
  {"name": "Letonia", "code": "lv", "delegate": "Meldra Rosenberg"},
  {"name": "Líbano", "code": "lb", "delegate": "Sarah Bou Jaoude"},
  {"name": "Macao", "code": "mo", "delegate": "Kris Fong"},
  {"name": "Malasia", "code": "my", "delegate": "Chloe Lim"},
  {"name": "Malta", "code": "mt", "delegate": "Julia Cluett"},
  {"name": "Martinica", "code": "mq", "delegate": "Celya Abatucci"},
  {"name": "Mauricio", "code": "mu", "delegate": "Aurelie Alcindor"},
  {"name": "Mayotte", "code": "yt", "delegate": "Nourya Aboutoihi"},
  {"name": "México", "code": "mx", "delegate": "Fatima Bosch"},
  {"name": "Moldavia", "code": "md", "delegate": "Mariana Ignat"},
  {"name": "Myanmar", "code": "mm", "delegate": "Myat Yadanar Soe"},
  {"name": "Namibia", "code": "na", "delegate": "Johanna Swartbooi"},
  {"name": "Nepal", "code": "np", "delegate": "Sanya Adhikari"},
  {"name": "Nicaragua", "code": "ni", "delegate": "Itza Castillo"},
  {"name": "Níger", "code": "ne", "delegate": "Zoulahatou Amadou"},
  {"name": "Nigeria", "code": "ng", "delegate": "Basil Onyinyechi"},
  {"name": "Noruega", "code": "no", "delegate": "Leonora Lysglimt-Rødland"},
  {"name": "Nueva Zelanda", "code": "nz", "delegate": "Abbigail Sturgin"},
  {"name": "Países Bajos", "code": "nl", "delegate": "Nathalie Mogbelzada"},
  {"name": "Pakistán", "code": "pk", "delegate": "Roma Riaz"},
  {"name": "Palestina", "code": "ps", "delegate": "Nadeen Ayoub"},
  {"name": "Panamá", "code": "pa", "delegate": "Mirna Caballini"},
  {"name": "Paraguay", "code": "py", "delegate": "Yanina Gomez"},
  {"name": "Perú", "code": "pe", "delegate": "Karla Bacigalupo"},
  {"name": "Portugal", "code": "pt", "delegate": "Camila Vitorino"},
  {"name": "Puerto Rico", "code": "pr", "delegate": "Zashely Alicea"},
  {"name": "Rep Checa", "code": "cz", "delegate": "Michaela Tomanova"},
  {"name": "Rep Dem Congo", "code": "cd", "delegate": "Dorcas Dienda"},
  {"name": "Rep Dominicana", "code": "do", "delegate": "Jennifer Ventura"},
  {"name": "Rumania", "code": "ro", "delegate": "Catalina Jacob"},
  {"name": "Rusia", "code": "ru", "delegate": "Anastasia Venza"},
  {"name": "Ruanda", "code": "rw", "delegate": "Solange Keita"},
  {"name": "Santa Lucía", "code": "lc", "delegate": "Shianne Smith"},
  {"name": "Senegal", "code": "sn", "delegate": "Camilla Diagne"},
  {"name": "Singapur", "code": "sg", "delegate": "Annika Sager"},
  {"name": "Sri Lanka", "code": "lk", "delegate": "Lihasha White"},
  {"name": "Suecia", "code": "se", "delegate": "Daniella Lundqvist"},
  {"name": "Suiza", "code": "ch", "delegate": "Naima Acosta"},
  {"name": "Surinam", "code": "sr", "delegate": "Chiara Wijntuin"},
  {"name": "Tailandia", "code": "th", "delegate": "Praveenar Singh"},
  {"name": "Tanzania", "code": "tz", "delegate": "Naisae Yona"},
  {"name": "Trinidad y Tobago", "code": "tt", "delegate": "Latifah Morris"},
  {"name": "Turquía", "code": "tr", "delegate": "Ceren Arslan"},
  {"name": "Ucrania", "code": "ua", "delegate": "Sofiya Tkachuk"},
  {"name": "Uruguay", "code": "uy", "delegate": "Valeria Baladan"},
  {"name": "Venezuela", "code": "ve", "delegate": "Stephany Abasali"},
  {"name": "Vietnam", "code": "vn", "delegate": "Hng Giang Nguyn"},
  {"name": "Zambia", "code": "zm", "delegate": "Kunda Mwamulima"},
  {"name": "Zimbabue", "code": "zw", "delegate": "Lyshanda Moyas"}
].sort((a, b) => a.name.localeCompare(b.name));